// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwdvgrvjtzswdlxngltw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZHZncnZqdHpzd2RseG5nbHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzExNTUsImV4cCI6MjA2NTkwNzE1NX0.zySX1qNYpcW5-n29RjWcZogOVCKrIO7dFz0r7_pgTI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);